name: Widgetbook Cloud

on: push

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        working-directory: widgetbook
        run: widgetbook cloud build push --api-key e46fd71253339be7d0a655e7f8b1a41423c644e35c7ef9e2b568282f06f05730
